apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  annotations:
    backstage.io/kubernetes-namespace: default
    backstage.io/kubernetes-label-selector: app=demo-nginx
spec:
  type: service
  lifecycle: experimental
  owner: user:default/HUIKUB
