apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-reader
rules:
# core API
- apiGroups: [ "" ]
  resources:
  - pods
  - services
  - configmaps
  - endpoints
  - namespaces
  - events
  verbs: [ get, list, watch ]
# apps
- apiGroups: [ "apps" ]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs: [ get, list, watch ]
# batch
- apiGroups: [ "batch" ]
  resources:
  - jobs
  - cronjobs
  verbs: [ get, list, watch ]
# networking
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "ingresses" ]
  verbs: [ get, list, watch ]
# autoscaling (HPA)
- apiGroups: [ "autoscaling" ]
  resources: [ "horizontalpodautoscalers" ]
  verbs: [ get, list, watch ]
# metrics (สำคัญสำหรับ CPU/Memory)
- apiGroups: [ "metrics.k8s.io" ]
  resources: [ "pods", "nodes" ]
  verbs: [ get, list, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-reader
subjects:
- kind: ServiceAccount
  name: backstage
  namespace: default
