apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nodejs-service-template
  title: NodeJS Service with Approval
  description: This Node.js template includes a full CI/CD pipeline, approval gate, and GitHub repo publishing.
spec:
  owner: HUIKUB
  type: service

  parameters:
  - title: Service Info
    required:
    - name
    - repoName
    properties:
      name:
        title: Name
        type: string
      repoName:
        title: Repository Name
        type: string
  - title: Approver Info
    required:
    - approver
    properties:
      approver:
        title: Approver
        type: string
        description: GitHub username or email of approver

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./content
      values:
        name: ${{ parameters.name }}

  - id: notify
    name: Notify Approver
    action: notification:send
    input:
      recipients: entity
      entityRefs:
      - user:default/${{ parameters.approver }}
      title: "Approval Needed"
      info: "Please approve manually in system (e.g., send Slack/Discord or Email)"
      severity: 'high'

  - id: wait-for-approval
    name: Await Approval
    action: wait:template
    input:
      reason: "Waiting for manual approval to continue creating the repository"
      timeout: 3600 # wait 1 hour max

  - id: publish
    name: Publish to GitHub
    action: publish:github
    input:
      repoUrl: github.com?owner=HUIKUB&repo=${{ parameters.repoName }}
      defaultBranch: main
      description: My service scaffolded by Backstage

  output:
    text:
    - "Here is your service workflow:"
    - "![Workflow](https://raw.githubusercontent.com/my-org/templates/main/content/assets/workflow-diagram.png)"
    links:
    - title: Repository
      url: ${{ steps['publish'].output.remoteUrl }}
