apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service
spec:
  owner: HUIKUB
  type: service

  parameters:
  - title: Fill in some steps
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        ui:options:
          rows: 5
  - title: Approver Info
    properties:
      approver:
        title: Approver
        type: string
        description: GitHub username of the approver

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./content
      values:
        name: ${{ parameters.name }}

  - id: create-pr
    name: Create PR Request for Approval
    action: publish:github:pull-request
    input:
      repoUrl: github.com?repo=service-requests&owner=myorg
      title: '[APPROVAL NEEDED] Request to create service: ${{ parameters.name }}'
      branchName: 'request-${{ parameters.name }}'
      description: |
        Request to create service: `${{ parameters.name }}`

        Please review and approve.

        Approver: @${{ parameters.approver }}

  - id: notify
    name: Notify
    action: notification:send
    input:
      recipients: entity
      entityRefs:
      - user:default/${{ parameters.approver }}
      title: 'Awaiting Approval'
      info: 'A PR has been created. Please approve to proceed.'
      severity: 'normal'

  output:
    links:
    - title: Approval PR
      url: ${{ steps['create-pr'].output.remoteUrl }}
