apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: example-nodejs-template
  title: Example Node.js Template
  description: An example template for the scaffolder that creates a simple Node.js service

spec:
  owner: HUIKUB
  type: service

  parameters:
  - title: Fill in some steps
    required:
    - name
    - repoName
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
      repoName:
        title: Repository Name
        type: string
        description: Repository name to create on GitHub

  - title: Approver Info
    properties:
      approver:
        title: Approver
        type: string
        description: GitHub username of the approver

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: ./content
      values:
        name: ${{ parameters.name }}

  - id: publish
    name: Publish to GitHub
    action: publish:github
    input:
      repoUrl: github.com?owner=HUIKUB&repo=${{ parameters.repoName }}
      defaultBranch: main
      description: My service scaffolded by Backstage

  output:
    links:
    - title: Approval PR
      url: ${{ steps['create-pr'].output.remoteUrl }}
